package de.cbos.service;

import javax.sql.DataSource;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

/**
 * Populates the configured datasource
 */
@Transactional
public class HsqldbSchemaAndDataPopulator implements InitializingBean {

	private JdbcTemplate template;
	
	public void afterPropertiesSet() throws Exception {
		Assert.notNull(template, "dataSource required");

		template
			.execute("CREATE TABLE IF NOT EXISTS USERS(USERNAME VARCHAR(30) NOT NULL PRIMARY KEY,"
	                + "PASSWORD VARCHAR(50) NOT NULL,"
	                + "ENABLED BOOLEAN NOT NULL,"
	                + "EMAIL VARCHAR_IGNORECASE(50) NOT NULL,"
	                + "CITY VARCHAR(50) NOT NULL,"
	                + "USERID INT NOT NULL,"
	                + "BIRTHDAY VARCHAR(50) NOT NULL,"
	                + "CONSTRAINT FK_GUESTBOOKENTRIES FOREIGN KEY(CONTENTID) REFERENCES GUESTBOOKENTRIES(CONTENTID));");
		template
			.execute("CREATE TABLE IF NOT EXISTS AUTHORITIES(USERNAME VARCHAR_IGNORECASE(50) NOT NULL,AUTHORITY VARCHAR_IGNORECASE(50) NOT NULL,CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME));");
        template
        	.execute("CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES(USERNAME,AUTHORITY);");
        
		template
		.execute("CREATE TABLE IF NOT EXISTS MODULES(MODULEID INTEGER NOT NULL PRIMARY KEY,"
				+ "MODULENAME VARCHAR(50) NOT NULL,"
                + "TYPE VARCHAR_IGNORECASE(50),"
				+ "LEFTPOSITION INT,"
                + "TOPPOSITION INT,"
				+ "PAGE INTEGER REFERENCES PAGE(PAGENAME));");
		
		template
		.execute("CREATE TABLE IF NOT EXISTS TEXTCONTAINERS(MODULEID INTEGER NOT NULL PRIMARY KEY,"
				+"CONSTRAINT FK_PARAGRAPHS FOREIGN KEY(MODULEID) REFERENCES PARAGRAPHS(MODULEID),"
				+"CONSTRAINT FK_MODULES FOREIGN KEY(MODULEID) REFERENCES MODULES(MODULEID));");
		
		template
		.execute("CREATE TABLE IF NOT EXISTS GUESTBOOKS(MODULEID INTEGER NOT NULL PRIMARY KEY,"
				+"CONSTRAINT FK_GUESTBOOKENTRIES FOREIGN KEY(MODULEID) REFERENCES GUESTBOOKENTRIES(MODULEID),"
				+"CONSTRAINT FK_MODULES FOREIGN KEY(MODULEID) REFERENCES MODULES(MODULEID));");
	
		template
		.execute("CREATE TABLE IF NOT EXISTS CONTENTS(CONTENTID INTEGER NOT NULL PRIMARY KEY,"
				+ "CONTENTNAME VARCHAR(50) NOT NULL,"
                + "CONTENTTYPE VARCHAR_IGNORECASE(50));");
		
		template
		.execute("CREATE TABLE IF NOT EXISTS GUESTBOOKENTRIES(CONTENTID INTEGER NOT NULL PRIMARY KEY,"
				+"GUESTBOOK INTEGER NOT NULL REFERENCES GUESTBOOK(MODULEID),"
				+"ENTRY VARCHAR(50),"
				+"CONSTRAINT FK_CONTENTS FOREIGN KEY(CONTENTID) REFERENCES CONTENTS(CONTENTID));");
		
		template
		.execute("CREATE TABLE IF NOT EXISTS PARAGRAPHS(CONTENTID INTEGER NOT NULL PRIMARY KEY,"
				+"TEXT VARCHAR(50) NOT NULL,"
				+"TEXTCONTAINER INTEGER NOT NULL REFERENCES TEXTCONTAINER(MODULEID)"
				+"CONSTRAINT FK_CONTENTS FOREIGN KEY REFERENCES CONTENTS(CONTENTID));");
		
		template
		.execute("CREATE TABLE IF NOT EXISTS PAGES(PAGENAME VARCHAR(50) NOT NULL PRIMARY KEY,"
				+"CONSTRAINT FK_LINK FOREIGN KEY(PAGEID) REFERENCES LINKS(PAGEID),"
				+"PAGEID INT NOT NULL,"
				+"CONSTRAINT FK_MODULES FOREIGN KEY(MODULEID) REFERENCES MODULES(MODULEID));");
		
		template
		.execute("CREATE TABLE IF NOT EXISTS NAVIGATIONS(MODULEID INTEGER NOT NULL PRIMARY KEY,"
				+"MAPPINGID INT,"
				+"CONSTRAINT FK_LINKS FOREIGN KEY(MAPPINGID) REFERENCES LINKS(MAPPINGID),"
				+"CONSTRAINT FK_MODULES FOREIGN KEY(MODULEID) REFERENCES MODULES(MODULEID));");
		
		template
		.execute("CREATE TABLE IF NOT EXISTS LINKS(CONTENTID INTEGER NOT NULL PRIMARY KEY,"
				+"NAVIGATION INTEGER NOT NULL REFERENCES NAVIGATIONS(MAPPINGID),"
				+"LINK VARCHAR(50),"
				+"MAPPINGID INT,"
				+"PAGE INTEGER NOT NULL REFERENCES PAGES(PAGEID)"
				+"CONSTRAINT FK_CONTENTS FOREIGN KEY REFERENCES CONTENTS(CONTENTID));");
        /**
         *  hard coded admin
         */
        template
        	.execute("INSERT INTO USERS(USERNAME,PASSWORD,ENABLED,EMAIL,CITY,BIRTHDAY,USERID) VALUES ('admin','admin',TRUE,'Admin@sample.de','Adminhausen','31.12.1992',-1);");
        template
    		.execute("INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES ('admin','ROLE_ADMIN');");
        
        /**
         *  hard coded default page
         */
        template
        	.execute("INSERT INTO PAGES(PAGENAME, PAGEID) VALUES ('home',-1)");
        
        template
        	.execute("INSERT INTO CONTENTS(CONTENTID, CONTENTNAME, CONTENTTYPE) VALUES (-1,'homelink', 'link')");
        
        template
        	.execute("INSERT INTO LINKS(LINK, CONTENTID) VALUES ('home',-1)");
	}
	
	/**
	 * Load external dataSource
	 * @param dataSource
	 */
	public void setDataSource(final DataSource dataSource) {
		this.template = new JdbcTemplate(dataSource);
	}
}

